name: Build and publish

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Install distrobuilder
        run: |
          sudo apt update
          sudo apt install -y debootstrap rsync gpg squashfs-tools git make
          git clone https://github.com/lxc/distrobuilder.git
          cd distrobuilder
          make
          sudo mv distrobuilder /usr/local/bin/
          sudo chmod +x /usr/local/bin/distrobuilder

      - name: Build
        run: |
          /usr/local/bin/distrobuilder
          sudo /usr/local/bin/distrobuilder build-lxc ubuntu.yaml