name: Build and publish

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Install distrobuilder
        run: |
          sudo apt update
          sudo apt install -y debootstrap rsync gpg squashfs-tools git make
          git clone https://github.com/lxc/distrobuilder.git
          cd distrobuilder
          make
          sudo mv $HOME/go/bin/distrobuilder /usr/local/bin/
          sudo chmod +x /usr/local/bin/distrobuilder

      - name: Build
        run: |
          sudo /usr/local/bin/distrobuilder build-lxc ubuntu.yaml

      - name: Rename artifact
        run: |
          mv mv rootfs.tar.xz itsm-ng-v${{ github.ref_name }}.tar.xz

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: itsm-ng-v${{ github.ref_name }}.tar.xz
          asset_name: itsm-ng-v${{ github.ref_name }}.tar.xz
          asset_content_type: application/x-xz

    
